### ISSUE TITLE
Conversion from pdf to cbz leaves blank pages

### ISSUE THREAD

**Issue by advert665** [binarynonsense/comic-book-reader#92] opened 2023-11-05 01:46 UTC
I really like this app, however it doesn't seem to be working correctly for me on windows when converting large 
(~350MB) pdfs to .cbz. While running the conversion, the app flashes black several times, and then when I look through the produced .cbz file, there are pages that are totally black and that have a size of 1kb. I've tried using an earlier version of the app and converting to ePub. Both have the same issue, with missing pages showing up as black images. Is the pdf just too large to work with this program?

Thanks in advance.

**Comment by binarynonsense** [comment] 2023-11-05 09:45
Hi, sorry you are having trouble with the program.

350MB shouldn't be a problem, so I don't think it's related to their size.

Does it happen with a particular set of pdf files or with anything you've tried? Do they display correctly in the reader or there are problems with them both in the reader and the converter?

I have never experienced the black flashes during the conversion (does the whole app become black, only the background and not the conversion window...?) with any file I've tried so I'd think it must be a problem with some particular file/s and the way the were built. Maybe the pdf library I'm using has problems reading those files for some reason... 

Are the 1kb pages pages that were incorrectly converted or extra pages generated during the conversion? (I seem to recall something weird like that happening with some preview files from humble bundle (but not with complete ones) I tried in the past to make some test, generating extra empty pages, but I'm not sure if I'm misremembering)

There's something you can try to see if you can get a better output. In the conversion tool, there are some pdf options in the advanced options you could try: in the advanced input options, change the PDF extraction option to "use 300dpi" or "use 72dpi".

If that doesn't work I would need a sample file to try to fix it (you could attach it here; use dropbox, meta or something similar and post the link here or send it to me via email, my contact address is in my website, you can check the url in my bio). Since I'm not having this problem with any of my test files I'd need one to reproduce the bug.

**Comment by advert665** [comment] 2023-11-05 22:35
Funnily enough, these are from Humble Bundle. It's the 'Creepy Comics'' Collection, which I think has just ended. In answer to your questions:

1) Having done a bit more testing, it appears it is just files from this Creepy Comics collection, other pdfs seem to work fine.
2) There are problems in the reader too (just noticed this). When clicking through pages, the window will sometimes flash black, before returning the GUI, and then you can move to the previous page and then back which will fix the issue. Interestingly, it seems to happen on the same pages as the ones that return black on the conversion (though these seem to change slightly each run).
3) The whole app flashes black, the conversion window and background both disappear.
4) I've tried those settings and the window still flashes, with the resulting files having the same issue.

I'll try to send you a sample pdf later once I've figured out the best way of doing that.

Thanks again!

**Comment by binarynonsense** [comment] 2023-11-06 08:40
From your answers, my first impression is that it may be a problem with the pdf library I use, having some kind of trouble correctly rendering those particular files for some reason (at least the way I use it as, to achieve what I need, I do some things with the library that may not be its most traditional use case).

If you manage to get me a sample file that triggers the bug I'll try to make some tests, but if the problem comes from the library I may not be able to fix it until they release a version capable of reading the files the way I need to or I figure out a way to do what I need with it that doesn't have that problem.

**Comment by binarynonsense** [comment] 2024-06-21 17:03
I'm closing this issue, at least for now, as it's been open for quite some time and without a test file I can't begin to try figuring out the problem.

**Closed by binarynonsense** 2024-06-21 17:03 UTC
Labels: type: bug, state: waiting for a test file
